name: Update GitHub Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: JuanDiegoCC02
          options: >-
            theme=tokyo-night
            &hide_border=true
            &area=true
            &days=31
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish activity graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout --orphan output
          git rm -rf . || true

          cp dist/activity-graph.svg activity-graph.svg

          git add activity-graph.svg
          git commit -m "Update activity graph"
          git push --force origin output
